Context Map Extractor Added(WithCtxMapExtractor)
tryfix/log pull request #5
Opened 2024-09-09 01:40 UTC by gmbyapa

- Context Map Extractor Added(WithCtxMapExtractor) for better perfomance
- Dependencies upgraded

2024-10-23 02:30 UTC, noelyahan requested changes

2024-10-23 02:30 UTC, noelyahan commented on go.mod
> +	github.com/logrusorgru/aurora v2.0.3+incompatible
we can update this to v4 (`github.com/logrusorgru/aurora/v4 v4.0.0`) module to resolve the go mod incompatibility

2024-10-23 21:01 UTC, gmbyapa commented on go.mod
> +	github.com/logrusorgru/aurora v2.0.3+incompatible
logrusorgru/aurora upgraded to v4

2024-10-28 03:06 UTC, noelyahan approved these changes

2024-11-12 20:47 UTC, merged